### ISSUE TITLE
Word spacing does not respect the natural spacing of the source code

### ISSUE THREAD

**Issue by juan88** [christopherkade/snippet#3]
I tried a very simple snippet in python and the image generated displays incorrect spacing between words in the source code making it difficult to read.

![screenshot](https://user-images.githubusercontent.com/7172489/34080107-b7754478-e317-11e7-97d0-afb16f5778d5.png)

The code I used is this one:

```python
while len(rulesToCheck) > 0:
	rule = rulesToCheck.pop()
	for proteinIdToCheck in getProteinsOfRule(rule):
		for ruleId in getRulesOfProtein(proteinIdToCheck):
			addRuleToGroup(ruleId, groupIndex)
			if ruleId in rulesToCheck:
				rulesToCheck.remove(ruleId)
	groupIndex = groupIndex + 1
```

**Comment by christopherkade** [comment]
Thanks for submitting an issue !

This problem should be fixed soon as it is related to a third party tool.

I'll update you once it is fixed.

**Comment by christopherkade** [comment]
The problem **should** be fixed now @juan88.

**Comment by juan88** [comment]
It is fixed indeed! Thank you very much!
